version: "3"

services:
  frontend:
    container_name: "React-todo-list"
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
      - ./frontend/.eslintrc.cjs:/frontend/.eslintrc.cjs
      - ./frontend/index.html:/frontend/index.html
      - ./frontend/tsconfig.json:/frontend/tsconfig.json
      - ./frontend/tsconfig.node.json:/frontend/tsconfig.node.json
      - ./frontend/vite.config.ts:/frontend/vite.config.ts
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]

  nginx:
    container_name: "Http-proxy-server"
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"
